In [3]:
import numpy as np
import tensorflow as tf   # need the libray for deep learing
from tensorflow import keras  # kearas you can search in chat gpt
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers  # import for layers
import pandas as pd # reading data

In [5]:
df = pd.DataFrame({       # Just a dummy data
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 21, 25, 20, 29, 21],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [7]:
df           # YOu can see there is just less data , but if you make a DL model you need huge data , in small data ML works better may be

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             21              11            1
12           0.55             25               2            0
13           0.70             20               6            0
14           0.12             29               1            1
15           0.30             21               9            1

In [8]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [24]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']       # Train test split

In [25]:
# Now we nee to min max scaler like scaling you can tell

In [26]:
# Normalization using min max scaliing  in DL , we use standardlization in Ml

In [27]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)  # formula of min max scaliing in DL

In [28]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.1250        0.909091
12       0.666667         0.3750        0.090909
13       0.866667         0.0625        0.454545
14       0.093333         0.6250        0.000000
15       0.333333         0.1250        0.727273

In [29]:
# Now you can see  all values will come between 0 and 1

Train test split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42,stratify=y)

After train test split now we can create model using tensor flow and keras

In [33]:
model = keras.Sequential([
   layers.Input(shape = (X_train.shape[1],)),  # shape
   layers.Dense(8, activation='relu'),
   layers.Dense(3, activation='relu'),
   layers.Dense(1, activation='sigmoid')

])
#

Optimizer or loss function use

In [36]:
model.compile(optimizer = 'sgd',loss = 'binary_crossentropy',metrics = ['accuracy'])

Forward and backward propagation

In [39]:
from re import VERBOSE
from enum import verify
history = model.fit(
    X_train.values,y_train.values,
    epochs = 100,  # you can search those in chat gpt to understand
    batch_size = 4,
    verbose = 1,
    validation_data = (X_test.values,y_test.values)
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6805 - val_accuracy: 0.7500 - val_loss: 0.6769
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6799 - val_accuracy: 0.7500 - val_loss: 0.6766
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6802 - val_accuracy: 0.7500 - val_loss: 0.6763
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6794 - val_accuracy: 0.7500 - val_loss: 0.6760
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6797 - val_accuracy: 0.7500 - val_loss: 0.6757
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6797 - val_accuracy: 0.7500 - val_loss: 0.6754
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6794 - val_accuracy: 0.7500 - val_loss: 0.6750
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6802 - val_accuracy: 0.7500 - val_loss: 0.6746
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6788 - val_accuracy: 0.7500 - val_loss: 0.6742
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6786 - val_accuracy: 0.7500 - val_loss: 0.6738
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6793 - val_accuracy: 0.7500 - val_loss: 0.6734
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6780 - val_accuracy: 0.7500 - val_loss: 0.6731
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6793 - val_accuracy: 0.7500 - val_loss: 0.6727
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6774 - val_accuracy: 0.7500 - val_loss: 0.6723
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6773 - val_accuracy: 0.7500 - val_loss: 0.6720
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6770 - val_accuracy: 0.7500 - val_loss: 0.6717
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6780 - val_accuracy: 0.7500 - val_loss: 0.6714
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6767 - val_accuracy: 0.7500 - val_loss: 0.6711
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6764 - val_accuracy: 0.7500 - val_loss: 0.6708
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6762 - val_accuracy: 0.7500 - val_loss: 0.6705
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6762 - val_accuracy: 0.7500 - val_loss: 0.6702
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6753 - val_accuracy: 0.7500 - val_loss: 0.6700
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6751 - val_accuracy: 0.7500 - val_loss: 0.6698
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6755 - val_accuracy: 0.7500 - val_loss: 0.6696
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6753 - val_accuracy: 0.7500 - val_loss: 0.6694
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6751 - val_accuracy: 0.7500 - val_loss: 0.6692
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6743 - val_accuracy: 0.7500 - val_loss: 0.6689
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6746 - val_accuracy: 0.7500 - val_loss: 0.6687
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6756 - val_accuracy: 0.7500 - val_loss: 0.6685
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6743 - val_accuracy: 0.7500 - val_loss: 0.6683
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6752 - val_accuracy: 0.7500 - val_loss: 0.6681
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6738 - val_accuracy: 0.7500 - val_loss: 0.6679
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6736 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6735 - val_accuracy: 0.7500 - val_loss: 0.6675
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6732 - val_accuracy: 0.7500 - val_loss: 0.6672
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6725 - val_accuracy: 0.7500 - val_loss: 0.6670
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6724 - val_accuracy: 0.7500 - val_loss: 0.6668
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6721 - val_accuracy: 0.7500 - val_loss: 0.6666
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6736 - val_accuracy: 0.7500 - val_loss: 0.6663
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6717 - val_accuracy: 0.7500 - val_loss: 0.6661
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6720 - val_accuracy: 0.7500 - val_loss: 0.6659
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6720 - val_accuracy: 0.7500 - val_loss: 0.6656
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6716 - val_accuracy: 0.7500 - val_loss: 0.6654
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6714 - val_accuracy: 0.7500 - val_loss: 0.6651
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6712 - val_accuracy: 0.7500 - val_loss: 0.6649
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6709 - val_accuracy: 0.7500 - val_loss: 0.6647
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6708 - val_accuracy: 0.7500 - val_loss: 0.6645
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6706 - val_accuracy: 0.7500 - val_loss: 0.6642
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6705 - val_accuracy: 0.7500 - val_loss: 0.6638
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6703 - val_accuracy: 0.7500 - val_loss: 0.6636
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6701 - val_accuracy: 0.7500 - val_loss: 0.6634
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6692 - val_accuracy: 0.7500 - val_loss: 0.6631
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5833 - loss: 0.6696 - val_accuracy: 0.7500 - val_loss: 0.6630
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6694 - val_accuracy: 0.7500 - val_loss: 0.6626
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6708 - val_accuracy: 0.7500 - val_loss: 0.6623
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6684 - val_accuracy: 0.7500 - val_loss: 0.6621
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6687 - val_accuracy: 0.7500 - val_loss: 0.6620
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6681 - val_accuracy: 0.7500 - val_loss: 0.6616
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6681 - val_accuracy: 0.7500 - val_loss: 0.6612
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6682 - val_accuracy: 0.7500 - val_loss: 0.6610
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6679 - val_accuracy: 0.7500 - val_loss: 0.6608
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6672 - val_accuracy: 0.7500 - val_loss: 0.6604
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6679 - val_accuracy: 0.7500 - val_loss: 0.6600
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6675 - val_accuracy: 0.7500 - val_loss: 0.6596
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6672 - val_accuracy: 0.7500 - val_loss: 0.6594
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6668 - val_accuracy: 0.7500 - val_loss: 0.6592
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6666 - val_accuracy: 0.7500 - val_loss: 0.6590
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6659 - val_accuracy: 0.7500 - val_loss: 0.6586
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6664 - val_accuracy: 0.7500 - val_loss: 0.6581
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6660 - val_accuracy: 0.7500 - val_loss: 0.6580
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6659 - val_accuracy: 0.7500 - val_loss: 0.6575
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6672 - val_accuracy: 0.7500 - val_loss: 0.6574
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6654 - val_accuracy: 0.7500 - val_loss: 0.6572
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5833 - loss: 0.6650 - val_accuracy: 0.7500 - val_loss: 0.6569
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6652 - val_accuracy: 0.7500 - val_loss: 0.6565
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6646 - val_accuracy: 0.7500 - val_loss: 0.6560
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6643 - val_accuracy: 0.7500 - val_loss: 0.6558
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6642 - val_accuracy: 0.7500 - val_loss: 0.6554
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.6640 - val_accuracy: 0.7500 - val_loss: 0.6552
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.6637 - val_accuracy: 0.7500 - val_loss: 0.6549
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.6634 - val_accuracy: 0.7500 - val_loss: 0.6545
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.6626 - val_accuracy: 0.7500 - val_loss: 0.6543
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.6623 - val_accuracy: 0.7500 - val_loss: 0.6541
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6630 - val_accuracy: 0.7500 - val_loss: 0.6536
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.6624 - val_accuracy: 0.7500 - val_loss: 0.6532
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6621 - val_accuracy: 0.7500 - val_loss: 0.6530
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5833 - loss: 0.6613 - val_accuracy: 0.7500 - val_loss: 0.6525
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6611 - val_accuracy: 1.0000 - val_loss: 0.6523
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.6608 - val_accuracy: 1.0000 - val_loss: 0.6520
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6611 - val_accuracy: 1.0000 - val_loss: 0.6515
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5833 - loss: 0.6623 - val_accuracy: 1.0000 - val_loss: 0.6511
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.6622 - val_accuracy: 1.0000 - val_loss: 0.6507
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5833 - loss: 0.6603 - val_accuracy: 1.0000 - val_loss: 0.6505
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5833 - loss: 0.6602 - val_accuracy: 1.0000 - val_loss: 0.6501
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6599 - val_accuracy: 1.0000 - val_loss: 0.6496
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6598 - val_accuracy: 1.0000 - val_loss: 0.6494
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6594 - val_accuracy: 1.0000 - val_loss: 0.6491
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6591 - val_accuracy: 1.0000 - val_loss: 0.6488
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6587 - val_accuracy: 1.0000 - val_loss: 0.6485
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6580 - val_accuracy: 1.0000 - val_loss: 0.6483